
package com.verimatrix.omi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import com.verimatrix.schemas.omitypes.Result;
import com.verimatrix.schemas.omitypes.SessionHandle;
import com.verimatrix.schemas.omitypes.UserLoginAttributes;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AdminMgmt", targetNamespace = "http://www.verimatrix.com/omi")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    com.verimatrix.schemas.iptvtypes.ObjectFactory.class,
    com.verimatrix.schemas.omitypes.ObjectFactory.class
})
public interface AdminMgmt {


    /**
     * 
     * @param result
     * @param sessionHandle
     * @param userAttributes
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/signOn")
    public void signOn(
        @WebParam(name = "userAttributes", partName = "userAttributes")
        UserLoginAttributes userAttributes,
        @WebParam(name = "sessionHandle", mode = WebParam.Mode.OUT, partName = "sessionHandle")
        Holder<SessionHandle> sessionHandle,
        @WebParam(name = "result", mode = WebParam.Mode.OUT, partName = "result")
        Holder<Result> result);

    /**
     * 
     * @param sessionHandle
     * @return
     *     returns com.verimatrix.schemas.omitypes.Result
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/signOff")
    @WebResult(name = "result", partName = "result")
    public Result signOff(
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

}
