
package com.verimatrix.omi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.verimatrix.schemas.omitypes.DeviceListResult;
import com.verimatrix.schemas.omitypes.DeviceTypeLicenseDataQuery;
import com.verimatrix.schemas.omitypes.DeviceTypeLicenseDataResult;
import com.verimatrix.schemas.omitypes.GroupLicenseDataQuery;
import com.verimatrix.schemas.omitypes.GroupLicenseDataResult;
import com.verimatrix.schemas.omitypes.LicenseGroupsQuery;
import com.verimatrix.schemas.omitypes.LicenseGroupsResult;
import com.verimatrix.schemas.omitypes.Network;
import com.verimatrix.schemas.omitypes.NetworkContentQuery;
import com.verimatrix.schemas.omitypes.NetworkContentResult;
import com.verimatrix.schemas.omitypes.NetworkDeviceListQuery;
import com.verimatrix.schemas.omitypes.NetworkListResult;
import com.verimatrix.schemas.omitypes.Result;
import com.verimatrix.schemas.omitypes.SessionHandle;
import com.verimatrix.schemas.omitypes.Site;
import com.verimatrix.schemas.omitypes.SiteListQuery;
import com.verimatrix.schemas.omitypes.SiteListResult;
import com.verimatrix.schemas.omitypes.SiteQuery;
import com.verimatrix.schemas.omitypes.SiteResult;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ConfigurationMgmt", targetNamespace = "http://www.verimatrix.com/omi")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    com.verimatrix.schemas.omitypes.ObjectFactory.class,
    com.verimatrix.schemas.iptvtypes.ObjectFactory.class
})
public interface ConfigurationMgmt {


    /**
     * 
     * @param sessionHandle
     * @param network
     * @return
     *     returns com.verimatrix.schemas.omitypes.Result
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/addNetwork")
    @WebResult(name = "result", partName = "result")
    public Result addNetwork(
        @WebParam(name = "network", partName = "network")
        Network network,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param network
     * @return
     *     returns com.verimatrix.schemas.omitypes.Result
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/modifyNetwork")
    @WebResult(name = "result", partName = "result")
    public Result modifyNetwork(
        @WebParam(name = "network", partName = "network")
        Network network,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param network
     * @return
     *     returns com.verimatrix.schemas.omitypes.Result
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/removeNetwork")
    @WebResult(name = "result", partName = "result")
    public Result removeNetwork(
        @WebParam(name = "network", partName = "network")
        Network network,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @return
     *     returns com.verimatrix.schemas.omitypes.NetworkListResult
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/getNetworkList")
    @WebResult(name = "queryResult", partName = "queryResult")
    public NetworkListResult getNetworkList(
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param networkDeviceListQuery
     * @param sessionHandle
     * @return
     *     returns com.verimatrix.schemas.omitypes.DeviceListResult
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/getNetworkDeviceList")
    @WebResult(name = "queryResult", partName = "queryResult")
    public DeviceListResult getNetworkDeviceList(
        @WebParam(name = "networkDeviceListQuery", partName = "networkDeviceListQuery")
        NetworkDeviceListQuery networkDeviceListQuery,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param networkContentQuery
     * @param sessionHandle
     * @return
     *     returns com.verimatrix.schemas.omitypes.NetworkContentResult
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/getNetworkContentList")
    @WebResult(name = "queryResult", partName = "queryResult")
    public NetworkContentResult getNetworkContentList(
        @WebParam(name = "networkContentQuery", partName = "networkContentQuery")
        NetworkContentQuery networkContentQuery,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param licenseGroupsQuery
     * @return
     *     returns com.verimatrix.schemas.omitypes.LicenseGroupsResult
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/getLicenseGroups")
    @WebResult(name = "queryResult", partName = "queryResult")
    public LicenseGroupsResult getLicenseGroups(
        @WebParam(name = "licenseGroupsQuery", partName = "licenseGroupsQuery")
        LicenseGroupsQuery licenseGroupsQuery,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param deviceTypeLicenseDataQuery
     * @return
     *     returns com.verimatrix.schemas.omitypes.DeviceTypeLicenseDataResult
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/getDeviceTypeLicenseData")
    @WebResult(name = "queryResult", partName = "queryResult")
    public DeviceTypeLicenseDataResult getDeviceTypeLicenseData(
        @WebParam(name = "deviceTypeLicenseDataQuery", partName = "deviceTypeLicenseDataQuery")
        DeviceTypeLicenseDataQuery deviceTypeLicenseDataQuery,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param groupLicenseDataQuery
     * @return
     *     returns com.verimatrix.schemas.omitypes.GroupLicenseDataResult
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/getGroupLicenseData")
    @WebResult(name = "queryResult", partName = "queryResult")
    public GroupLicenseDataResult getGroupLicenseData(
        @WebParam(name = "groupLicenseDataQuery", partName = "groupLicenseDataQuery")
        GroupLicenseDataQuery groupLicenseDataQuery,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param site
     * @param sessionHandle
     * @return
     *     returns com.verimatrix.schemas.omitypes.Result
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/addSite")
    @WebResult(name = "result", partName = "result")
    public Result addSite(
        @WebParam(name = "site", partName = "site")
        Site site,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param site
     * @param sessionHandle
     * @return
     *     returns com.verimatrix.schemas.omitypes.Result
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/modifySite")
    @WebResult(name = "result", partName = "result")
    public Result modifySite(
        @WebParam(name = "site", partName = "site")
        Site site,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param site
     * @param sessionHandle
     * @return
     *     returns com.verimatrix.schemas.omitypes.Result
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/removeSite")
    @WebResult(name = "result", partName = "result")
    public Result removeSite(
        @WebParam(name = "site", partName = "site")
        Site site,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param siteQuery
     * @param sessionHandle
     * @return
     *     returns com.verimatrix.schemas.omitypes.SiteResult
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/getSite")
    @WebResult(name = "queryResult", partName = "queryResult")
    public SiteResult getSite(
        @WebParam(name = "siteQuery", partName = "siteQuery")
        SiteQuery siteQuery,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param siteListQuery
     * @return
     *     returns com.verimatrix.schemas.omitypes.SiteListResult
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/getSiteList")
    @WebResult(name = "queryResult", partName = "queryResult")
    public SiteListResult getSiteList(
        @WebParam(name = "siteListQuery", partName = "siteListQuery")
        SiteListQuery siteListQuery,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

}
