
package com.verimatrix.omi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.verimatrix.schemas.omitypes.ContentEventQuery;
import com.verimatrix.schemas.omitypes.ContentEventResult;
import com.verimatrix.schemas.omitypes.ContentList;
import com.verimatrix.schemas.omitypes.ContentListQuery;
import com.verimatrix.schemas.omitypes.ContentListResult;
import com.verimatrix.schemas.omitypes.ContentOnNetworkQuery;
import com.verimatrix.schemas.omitypes.EventList;
import com.verimatrix.schemas.omitypes.NetworkContent;
import com.verimatrix.schemas.omitypes.NetworkContentEncryptionQuery;
import com.verimatrix.schemas.omitypes.NetworkContentEncryptionResult;
import com.verimatrix.schemas.omitypes.NetworkContentIdQuery;
import com.verimatrix.schemas.omitypes.NetworkContentIdResult;
import com.verimatrix.schemas.omitypes.NetworkContentResult;
import com.verimatrix.schemas.omitypes.NetworkContentTypeEncryptionQuery;
import com.verimatrix.schemas.omitypes.NetworkContentTypeEncryptionResult;
import com.verimatrix.schemas.omitypes.Result;
import com.verimatrix.schemas.omitypes.ResultList;
import com.verimatrix.schemas.omitypes.SessionHandle;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ContentMgmt", targetNamespace = "http://www.verimatrix.com/omi")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    com.verimatrix.schemas.iptvtypes.ObjectFactory.class,
    com.verimatrix.schemas.omitypes.ObjectFactory.class
})
public interface ContentMgmt {


    /**
     * 
     * @param sessionHandle
     * @param eventList
     * @return
     *     returns com.verimatrix.schemas.omitypes.ResultList
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/addEvents")
    @WebResult(name = "resultList", partName = "resultList")
    public ResultList addEvents(
        @WebParam(name = "eventList", partName = "eventList")
        EventList eventList,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param eventList
     * @return
     *     returns com.verimatrix.schemas.omitypes.ResultList
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/removeEvents")
    @WebResult(name = "resultList", partName = "resultList")
    public ResultList removeEvents(
        @WebParam(name = "eventList", partName = "eventList")
        EventList eventList,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param contentList
     * @return
     *     returns com.verimatrix.schemas.omitypes.ResultList
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/addContent")
    @WebResult(name = "resultList", partName = "resultList")
    public ResultList addContent(
        @WebParam(name = "contentList", partName = "contentList")
        ContentList contentList,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param contentList
     * @return
     *     returns com.verimatrix.schemas.omitypes.ResultList
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/removeContent")
    @WebResult(name = "resultList", partName = "resultList")
    public ResultList removeContent(
        @WebParam(name = "contentList", partName = "contentList")
        ContentList contentList,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param contentListQuery
     * @param sessionHandle
     * @return
     *     returns com.verimatrix.schemas.omitypes.ContentListResult
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/getContentList")
    @WebResult(name = "queryResult", partName = "queryResult")
    public ContentListResult getContentList(
        @WebParam(name = "contentListQuery", partName = "contentListQuery")
        ContentListQuery contentListQuery,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param contentEventQuery
     * @return
     *     returns com.verimatrix.schemas.omitypes.ContentEventResult
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/getContentEvents")
    @WebResult(name = "queryResult", partName = "queryResult")
    public ContentEventResult getContentEvents(
        @WebParam(name = "contentEventQuery", partName = "contentEventQuery")
        ContentEventQuery contentEventQuery,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param networkContent
     * @return
     *     returns com.verimatrix.schemas.omitypes.Result
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/addContentToNetwork")
    @WebResult(name = "result", partName = "result")
    public Result addContentToNetwork(
        @WebParam(name = "networkContent", partName = "networkContent")
        NetworkContent networkContent,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param networkContent
     * @return
     *     returns com.verimatrix.schemas.omitypes.Result
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/removeContentFromNetwork")
    @WebResult(name = "result", partName = "result")
    public Result removeContentFromNetwork(
        @WebParam(name = "networkContent", partName = "networkContent")
        NetworkContent networkContent,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param networkContentEncryptionQuery
     * @param sessionHandle
     * @return
     *     returns com.verimatrix.schemas.omitypes.NetworkContentEncryptionResult
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/getNetworkContentEncryptionStatus")
    @WebResult(name = "queryResult", partName = "queryResult")
    public NetworkContentEncryptionResult getNetworkContentEncryptionStatus(
        @WebParam(name = "networkContentEncryptionQuery", partName = "networkContentEncryptionQuery")
        NetworkContentEncryptionQuery networkContentEncryptionQuery,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param networkContent
     * @return
     *     returns com.verimatrix.schemas.omitypes.Result
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/modifyContentOnNetwork")
    @WebResult(name = "result", partName = "result")
    public Result modifyContentOnNetwork(
        @WebParam(name = "networkContent", partName = "networkContent")
        NetworkContent networkContent,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param contentOnNetworkQuery
     * @return
     *     returns com.verimatrix.schemas.omitypes.NetworkContentResult
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/getContentOnNetwork")
    @WebResult(name = "queryResult", partName = "queryResult")
    public NetworkContentResult getContentOnNetwork(
        @WebParam(name = "contentOnNetworkQuery", partName = "contentOnNetworkQuery")
        ContentOnNetworkQuery contentOnNetworkQuery,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param networkContentTypeEncryptionQuery
     * @return
     *     returns com.verimatrix.schemas.omitypes.NetworkContentTypeEncryptionResult
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/getNetworkContentTypeEncryptionStatus")
    @WebResult(name = "queryResult", partName = "queryResult")
    public NetworkContentTypeEncryptionResult getNetworkContentTypeEncryptionStatus(
        @WebParam(name = "networkContentTypeEncryptionQuery", partName = "networkContentTypeEncryptionQuery")
        NetworkContentTypeEncryptionQuery networkContentTypeEncryptionQuery,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param networkContentIdQuery
     * @return
     *     returns com.verimatrix.schemas.omitypes.NetworkContentIdResult
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/getNetworkContentIdList")
    @WebResult(name = "queryResult", partName = "queryResult")
    public NetworkContentIdResult getNetworkContentIdList(
        @WebParam(name = "networkContentIdQuery", partName = "networkContentIdQuery")
        NetworkContentIdQuery networkContentIdQuery,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

}
