
package com.verimatrix.omi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.verimatrix.schemas.omitypes.Device;
import com.verimatrix.schemas.omitypes.DeviceList;
import com.verimatrix.schemas.omitypes.DeviceListQuery;
import com.verimatrix.schemas.omitypes.DeviceListResult;
import com.verimatrix.schemas.omitypes.DevicePair;
import com.verimatrix.schemas.omitypes.DevicePinList;
import com.verimatrix.schemas.omitypes.DevicePurse;
import com.verimatrix.schemas.omitypes.DeviceRegion;
import com.verimatrix.schemas.omitypes.NetworkDeviceIdQuery;
import com.verimatrix.schemas.omitypes.NetworkDeviceIdResult;
import com.verimatrix.schemas.omitypes.Result;
import com.verimatrix.schemas.omitypes.ResultList;
import com.verimatrix.schemas.omitypes.STBDevice;
import com.verimatrix.schemas.omitypes.STBPairingQuery;
import com.verimatrix.schemas.omitypes.STBPairingResult;
import com.verimatrix.schemas.omitypes.SessionHandle;
import com.verimatrix.schemas.omitypes.SmartCardDevice;
import com.verimatrix.schemas.omitypes.SmartCardPairingQuery;
import com.verimatrix.schemas.omitypes.SmartCardPairingResult;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DeviceMgmt", targetNamespace = "http://www.verimatrix.com/omi")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    com.verimatrix.schemas.omitypes.ObjectFactory.class,
    com.verimatrix.schemas.iptvtypes.ObjectFactory.class
})
public interface DeviceMgmt {


    /**
     * 
     * @param sessionHandle
     * @param deviceList
     * @return
     *     returns com.verimatrix.schemas.omitypes.ResultList
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/addDevices")
    @WebResult(name = "resultList", partName = "resultList")
    public ResultList addDevices(
        @WebParam(name = "deviceList", partName = "deviceList")
        DeviceList deviceList,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param deviceList
     * @return
     *     returns com.verimatrix.schemas.omitypes.ResultList
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/modifyDevices")
    @WebResult(name = "resultList", partName = "resultList")
    public ResultList modifyDevices(
        @WebParam(name = "deviceList", partName = "deviceList")
        DeviceList deviceList,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param deviceList
     * @return
     *     returns com.verimatrix.schemas.omitypes.ResultList
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/removeDevices")
    @WebResult(name = "resultList", partName = "resultList")
    public ResultList removeDevices(
        @WebParam(name = "deviceList", partName = "deviceList")
        DeviceList deviceList,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param deviceList
     * @return
     *     returns com.verimatrix.schemas.omitypes.ResultList
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/clearDevices")
    @WebResult(name = "resultList", partName = "resultList")
    public ResultList clearDevices(
        @WebParam(name = "deviceList", partName = "deviceList")
        DeviceList deviceList,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param device
     * @return
     *     returns com.verimatrix.schemas.omitypes.Result
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/refreshDeviceKeys")
    @WebResult(name = "result", partName = "result")
    public Result refreshDeviceKeys(
        @WebParam(name = "device", partName = "device")
        Device device,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param device
     * @return
     *     returns com.verimatrix.schemas.omitypes.Result
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/resetDevicePins")
    @WebResult(name = "result", partName = "result")
    public Result resetDevicePins(
        @WebParam(name = "device", partName = "device")
        Device device,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param devicePinList
     * @param device
     * @return
     *     returns com.verimatrix.schemas.omitypes.Result
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/setDevicePins")
    @WebResult(name = "result", partName = "result")
    public Result setDevicePins(
        @WebParam(name = "device", partName = "device")
        Device device,
        @WebParam(name = "devicePinList", partName = "devicePinList")
        DevicePinList devicePinList,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param deviceRegion
     * @param device
     * @return
     *     returns com.verimatrix.schemas.omitypes.Result
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/setDeviceRegion")
    @WebResult(name = "result", partName = "result")
    public Result setDeviceRegion(
        @WebParam(name = "device", partName = "device")
        Device device,
        @WebParam(name = "deviceRegion", partName = "deviceRegion")
        DeviceRegion deviceRegion,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param devicePurse
     * @param sessionHandle
     * @param device
     * @return
     *     returns com.verimatrix.schemas.omitypes.Result
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/setDevicePurse")
    @WebResult(name = "result", partName = "result")
    public Result setDevicePurse(
        @WebParam(name = "device", partName = "device")
        Device device,
        @WebParam(name = "devicePurse", partName = "devicePurse")
        DevicePurse devicePurse,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param slaveDeviceList
     * @param sessionHandle
     * @param masterDevice
     * @return
     *     returns com.verimatrix.schemas.omitypes.Result
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/joinDevices")
    @WebResult(name = "result", partName = "result")
    public Result joinDevices(
        @WebParam(name = "masterDevice", partName = "masterDevice")
        Device masterDevice,
        @WebParam(name = "slaveDeviceList", partName = "slaveDeviceList")
        DeviceList slaveDeviceList,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param deviceList
     * @return
     *     returns com.verimatrix.schemas.omitypes.ResultList
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/unjoinDevices")
    @WebResult(name = "resultList", partName = "resultList")
    public ResultList unjoinDevices(
        @WebParam(name = "deviceList", partName = "deviceList")
        DeviceList deviceList,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param devicePair
     * @param sessionHandle
     * @return
     *     returns com.verimatrix.schemas.omitypes.Result
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/addDevicePair")
    @WebResult(name = "result", partName = "result")
    public Result addDevicePair(
        @WebParam(name = "devicePair", partName = "devicePair")
        DevicePair devicePair,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param devicePair
     * @param sessionHandle
     * @return
     *     returns com.verimatrix.schemas.omitypes.Result
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/removeDevicePair")
    @WebResult(name = "result", partName = "result")
    public Result removeDevicePair(
        @WebParam(name = "devicePair", partName = "devicePair")
        DevicePair devicePair,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param smartCardDevice
     * @param sessionHandle
     * @return
     *     returns com.verimatrix.schemas.omitypes.Result
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/removeSmartCardDevicePairing")
    @WebResult(name = "result", partName = "result")
    public Result removeSmartCardDevicePairing(
        @WebParam(name = "smartCardDevice", partName = "smartCardDevice")
        SmartCardDevice smartCardDevice,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param stbDevice
     * @return
     *     returns com.verimatrix.schemas.omitypes.Result
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/removeSTBDevicePairing")
    @WebResult(name = "result", partName = "result")
    public Result removeSTBDevicePairing(
        @WebParam(name = "stbDevice", partName = "stbDevice")
        STBDevice stbDevice,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param devicePair
     * @param sessionHandle
     * @return
     *     returns com.verimatrix.schemas.omitypes.Result
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/checkDevicePair")
    @WebResult(name = "result", partName = "result")
    public Result checkDevicePair(
        @WebParam(name = "devicePair", partName = "devicePair")
        DevicePair devicePair,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param smartCardPairingQuery
     * @return
     *     returns com.verimatrix.schemas.omitypes.SmartCardPairingResult
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/getSmartCardPairing")
    @WebResult(name = "queryResult", partName = "queryResult")
    public SmartCardPairingResult getSmartCardPairing(
        @WebParam(name = "smartCardPairingQuery", partName = "smartCardPairingQuery")
        SmartCardPairingQuery smartCardPairingQuery,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param stbPairingQuery
     * @return
     *     returns com.verimatrix.schemas.omitypes.STBPairingResult
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/getSTBPairing")
    @WebResult(name = "queryResult", partName = "queryResult")
    public STBPairingResult getSTBPairing(
        @WebParam(name = "stbPairingQuery", partName = "stbPairingQuery")
        STBPairingQuery stbPairingQuery,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param deviceListQuery
     * @return
     *     returns com.verimatrix.schemas.omitypes.DeviceListResult
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/getDeviceList")
    @WebResult(name = "queryResult", partName = "queryResult")
    public DeviceListResult getDeviceList(
        @WebParam(name = "deviceListQuery", partName = "deviceListQuery")
        DeviceListQuery deviceListQuery,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param deviceList
     * @return
     *     returns com.verimatrix.schemas.omitypes.ResultList
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/enableDevices")
    @WebResult(name = "resultList", partName = "resultList")
    public ResultList enableDevices(
        @WebParam(name = "deviceList", partName = "deviceList")
        DeviceList deviceList,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param deviceList
     * @return
     *     returns com.verimatrix.schemas.omitypes.ResultList
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/disableDevices")
    @WebResult(name = "resultList", partName = "resultList")
    public ResultList disableDevices(
        @WebParam(name = "deviceList", partName = "deviceList")
        DeviceList deviceList,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param networkDeviceIdListQuery
     * @return
     *     returns com.verimatrix.schemas.omitypes.NetworkDeviceIdResult
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/getNetworkDeviceIdList")
    @WebResult(name = "queryResult", partName = "queryResult")
    public NetworkDeviceIdResult getNetworkDeviceIdList(
        @WebParam(name = "networkDeviceIdListQuery", partName = "networkDeviceIdListQuery")
        NetworkDeviceIdQuery networkDeviceIdListQuery,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param device
     * @return
     *     returns com.verimatrix.schemas.omitypes.Result
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/verifyDevice")
    @WebResult(name = "result", partName = "result")
    public Result verifyDevice(
        @WebParam(name = "device", partName = "device")
        Device device,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param device
     * @return
     *     returns com.verimatrix.schemas.omitypes.Result
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/refreshDeviceEntitlements")
    @WebResult(name = "result", partName = "result")
    public Result refreshDeviceEntitlements(
        @WebParam(name = "device", partName = "device")
        Device device,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

}
