
package com.verimatrix.omi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.verimatrix.schemas.omitypes.DeviceDomainListQuery;
import com.verimatrix.schemas.omitypes.Domain;
import com.verimatrix.schemas.omitypes.DomainDeviceList;
import com.verimatrix.schemas.omitypes.DomainDeviceListQuery;
import com.verimatrix.schemas.omitypes.DomainDeviceListResult;
import com.verimatrix.schemas.omitypes.DomainList;
import com.verimatrix.schemas.omitypes.DomainListQuery;
import com.verimatrix.schemas.omitypes.DomainListResult;
import com.verimatrix.schemas.omitypes.ResultList;
import com.verimatrix.schemas.omitypes.SessionHandle;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DomainMgmt", targetNamespace = "http://www.verimatrix.com/omi")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    com.verimatrix.schemas.omitypes.ObjectFactory.class,
    com.verimatrix.schemas.iptvtypes.ObjectFactory.class
})
public interface DomainMgmt {


    /**
     * 
     * @param sessionHandle
     * @param domainList
     * @return
     *     returns com.verimatrix.schemas.omitypes.ResultList
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/addDomains")
    @WebResult(name = "resultList", partName = "resultList")
    public ResultList addDomains(
        @WebParam(name = "domainList", partName = "domainList")
        DomainList domainList,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param domainList
     * @return
     *     returns com.verimatrix.schemas.omitypes.ResultList
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/modifyDomains")
    @WebResult(name = "resultList", partName = "resultList")
    public ResultList modifyDomains(
        @WebParam(name = "domainList", partName = "domainList")
        DomainList domainList,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param domainList
     * @return
     *     returns com.verimatrix.schemas.omitypes.ResultList
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/removeDomains")
    @WebResult(name = "resultList", partName = "resultList")
    public ResultList removeDomains(
        @WebParam(name = "domainList", partName = "domainList")
        DomainList domainList,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param domain
     * @param deviceList
     * @return
     *     returns com.verimatrix.schemas.omitypes.ResultList
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/addDomainDevices")
    @WebResult(name = "resultList", partName = "resultList")
    public ResultList addDomainDevices(
        @WebParam(name = "domain", partName = "domain")
        Domain domain,
        @WebParam(name = "deviceList", partName = "deviceList")
        DomainDeviceList deviceList,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param domain
     * @param deviceList
     * @return
     *     returns com.verimatrix.schemas.omitypes.ResultList
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/modifyDomainDevices")
    @WebResult(name = "resultList", partName = "resultList")
    public ResultList modifyDomainDevices(
        @WebParam(name = "domain", partName = "domain")
        Domain domain,
        @WebParam(name = "deviceList", partName = "deviceList")
        DomainDeviceList deviceList,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param domain
     * @param deviceList
     * @return
     *     returns com.verimatrix.schemas.omitypes.ResultList
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/removeDomainDevices")
    @WebResult(name = "resultList", partName = "resultList")
    public ResultList removeDomainDevices(
        @WebParam(name = "domain", partName = "domain")
        Domain domain,
        @WebParam(name = "deviceList", partName = "deviceList")
        DomainDeviceList deviceList,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param domainListQuery
     * @return
     *     returns com.verimatrix.schemas.omitypes.DomainListResult
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/getDomainList")
    @WebResult(name = "queryResult", partName = "queryResult")
    public DomainListResult getDomainList(
        @WebParam(name = "domainListQuery", partName = "domainListQuery")
        DomainListQuery domainListQuery,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param domainDeviceListQuery
     * @return
     *     returns com.verimatrix.schemas.omitypes.DomainDeviceListResult
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/getDomainDeviceList")
    @WebResult(name = "queryResult", partName = "queryResult")
    public DomainDeviceListResult getDomainDeviceList(
        @WebParam(name = "domainDeviceListQuery", partName = "domainDeviceListQuery")
        DomainDeviceListQuery domainDeviceListQuery,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param deviceDomainListQuery
     * @return
     *     returns com.verimatrix.schemas.omitypes.DomainListResult
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/getDeviceDomainList")
    @WebResult(name = "queryResult", partName = "queryResult")
    public DomainListResult getDeviceDomainList(
        @WebParam(name = "deviceDomainListQuery", partName = "deviceDomainListQuery")
        DeviceDomainListQuery deviceDomainListQuery,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

}
