
package com.verimatrix.omi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.verimatrix.schemas.omitypes.DeviceEntitlementQuery;
import com.verimatrix.schemas.omitypes.DeviceEntitlementResult;
import com.verimatrix.schemas.omitypes.DomainEntitlementQuery;
import com.verimatrix.schemas.omitypes.DomainEntitlementResult;
import com.verimatrix.schemas.omitypes.EntitledEntity;
import com.verimatrix.schemas.omitypes.EntitledEntityList;
import com.verimatrix.schemas.omitypes.EntitlementList;
import com.verimatrix.schemas.omitypes.EntitlementListQuery;
import com.verimatrix.schemas.omitypes.EntitlementListResult;
import com.verimatrix.schemas.omitypes.EventList;
import com.verimatrix.schemas.omitypes.EventPackageQuery;
import com.verimatrix.schemas.omitypes.EventPackageResult;
import com.verimatrix.schemas.omitypes.Package;
import com.verimatrix.schemas.omitypes.PackageEventQuery;
import com.verimatrix.schemas.omitypes.PackageEventResult;
import com.verimatrix.schemas.omitypes.PackageList;
import com.verimatrix.schemas.omitypes.PackageListQuery;
import com.verimatrix.schemas.omitypes.PackageListResult;
import com.verimatrix.schemas.omitypes.Result;
import com.verimatrix.schemas.omitypes.ResultList;
import com.verimatrix.schemas.omitypes.RetailerEntitlementQuery;
import com.verimatrix.schemas.omitypes.RetailerEntitlementResult;
import com.verimatrix.schemas.omitypes.SessionHandle;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "EntitlementMgmt", targetNamespace = "http://www.verimatrix.com/omi")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    com.verimatrix.schemas.iptvtypes.ObjectFactory.class,
    com.verimatrix.schemas.omitypes.ObjectFactory.class
})
public interface EntitlementMgmt {


    /**
     * 
     * @param sessionHandle
     * @param entitlementList
     * @return
     *     returns com.verimatrix.schemas.omitypes.ResultList
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/addEntitlements")
    @WebResult(name = "resultList", partName = "resultList")
    public ResultList addEntitlements(
        @WebParam(name = "entitlementList", partName = "entitlementList")
        EntitlementList entitlementList,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param entitlementList
     * @return
     *     returns com.verimatrix.schemas.omitypes.ResultList
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/modifyEntitlements")
    @WebResult(name = "resultList", partName = "resultList")
    public ResultList modifyEntitlements(
        @WebParam(name = "entitlementList", partName = "entitlementList")
        EntitlementList entitlementList,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param entitlementList
     * @return
     *     returns com.verimatrix.schemas.omitypes.ResultList
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/removeEntitlements")
    @WebResult(name = "resultList", partName = "resultList")
    public ResultList removeEntitlements(
        @WebParam(name = "entitlementList", partName = "entitlementList")
        EntitlementList entitlementList,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param entitledEntityList
     * @return
     *     returns com.verimatrix.schemas.omitypes.ResultList
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/removeAllEntitlements")
    @WebResult(name = "resultList", partName = "resultList")
    public ResultList removeAllEntitlements(
        @WebParam(name = "entitledEntityList", partName = "entitledEntityList")
        EntitledEntityList entitledEntityList,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param entitledEntity
     * @return
     *     returns com.verimatrix.schemas.omitypes.Result
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/stopPreEntitlements")
    @WebResult(name = "result", partName = "result")
    public Result stopPreEntitlements(
        @WebParam(name = "entitledEntity", partName = "entitledEntity")
        EntitledEntity entitledEntity,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param entitlementQuery
     * @return
     *     returns com.verimatrix.schemas.omitypes.DeviceEntitlementResult
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/getDeviceEntitlements")
    @WebResult(name = "queryResult", partName = "queryResult")
    public DeviceEntitlementResult getDeviceEntitlements(
        @WebParam(name = "entitlementQuery", partName = "entitlementQuery")
        DeviceEntitlementQuery entitlementQuery,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param entitlementQuery
     * @return
     *     returns com.verimatrix.schemas.omitypes.DomainEntitlementResult
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/getDomainEntitlements")
    @WebResult(name = "queryResult", partName = "queryResult")
    public DomainEntitlementResult getDomainEntitlements(
        @WebParam(name = "entitlementQuery", partName = "entitlementQuery")
        DomainEntitlementQuery entitlementQuery,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param packageList
     * @return
     *     returns com.verimatrix.schemas.omitypes.ResultList
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/addPackages")
    @WebResult(name = "resultList", partName = "resultList")
    public ResultList addPackages(
        @WebParam(name = "packageList", partName = "packageList")
        PackageList packageList,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param packageList
     * @return
     *     returns com.verimatrix.schemas.omitypes.ResultList
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/removePackages")
    @WebResult(name = "resultList", partName = "resultList")
    public ResultList removePackages(
        @WebParam(name = "packageList", partName = "packageList")
        PackageList packageList,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param _package
     * @param eventList
     * @return
     *     returns com.verimatrix.schemas.omitypes.ResultList
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/addEventsToPackage")
    @WebResult(name = "resultList", partName = "resultList")
    public ResultList addEventsToPackage(
        @WebParam(name = "package", partName = "package")
        Package _package,
        @WebParam(name = "eventList", partName = "eventList")
        EventList eventList,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param _package
     * @param eventList
     * @return
     *     returns com.verimatrix.schemas.omitypes.ResultList
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/removeEventsFromPackage")
    @WebResult(name = "resultList", partName = "resultList")
    public ResultList removeEventsFromPackage(
        @WebParam(name = "package", partName = "package")
        Package _package,
        @WebParam(name = "eventList", partName = "eventList")
        EventList eventList,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param packageListQuery
     * @return
     *     returns com.verimatrix.schemas.omitypes.PackageListResult
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/getPackageList")
    @WebResult(name = "queryResult", partName = "queryResult")
    public PackageListResult getPackageList(
        @WebParam(name = "packageListQuery", partName = "packageListQuery")
        PackageListQuery packageListQuery,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param packageEventQuery
     * @param sessionHandle
     * @return
     *     returns com.verimatrix.schemas.omitypes.PackageEventResult
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/getPackageEvents")
    @WebResult(name = "queryResult", partName = "queryResult")
    public PackageEventResult getPackageEvents(
        @WebParam(name = "packageEventQuery", partName = "packageEventQuery")
        PackageEventQuery packageEventQuery,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param entitlementListQuery
     * @return
     *     returns com.verimatrix.schemas.omitypes.EntitlementListResult
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/getEntitlementList")
    @WebResult(name = "queryResult", partName = "queryResult")
    public EntitlementListResult getEntitlementList(
        @WebParam(name = "entitlementListQuery", partName = "entitlementListQuery")
        EntitlementListQuery entitlementListQuery,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param eventPackageQuery
     * @param sessionHandle
     * @return
     *     returns com.verimatrix.schemas.omitypes.EventPackageResult
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/getEventPackages")
    @WebResult(name = "queryResult", partName = "queryResult")
    public EventPackageResult getEventPackages(
        @WebParam(name = "eventPackageQuery", partName = "eventPackageQuery")
        EventPackageQuery eventPackageQuery,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param packageList
     * @return
     *     returns com.verimatrix.schemas.omitypes.ResultList
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/modifyPackages")
    @WebResult(name = "resultList", partName = "resultList")
    public ResultList modifyPackages(
        @WebParam(name = "packageList", partName = "packageList")
        PackageList packageList,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

    /**
     * 
     * @param sessionHandle
     * @param entitlementQuery
     * @return
     *     returns com.verimatrix.schemas.omitypes.RetailerEntitlementResult
     */
    @WebMethod(action = "http://www.verimatrix.com/omi/getRetailerEntitlements")
    @WebResult(name = "queryResult", partName = "queryResult")
    public RetailerEntitlementResult getRetailerEntitlements(
        @WebParam(name = "entitlementQuery", partName = "entitlementQuery")
        RetailerEntitlementQuery entitlementQuery,
        @WebParam(name = "sessionHandle", partName = "sessionHandle")
        SessionHandle sessionHandle);

}
